# H2 (dev)
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:h2:mem:reserva;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.h2.Driver